In [1]:
import pandas as pd

feature_path = "data/processed/feature/feature_test.parquet"
df = pd.read_parquet(feature_path)
df.head()

,platform,source_type,source_query,seed_hashtag,video_id,create_time_ts,caption_raw,hashtags,author_id,author_username,...,is_trending_audio,content_type,appearance_type,has_product_link,crawl_at,crawl_batch_id,raw_payload_path,sentiment_score,visual_embedding,content_cluster_id
0,tiktok,hashtag,nikeshoes,nikeshoes,mock_video_nikeshoes_0,1772930459,Mock video about nikeshoes #nikeshoes #fashion,"[nikeshoes, fashion, style]",mock_author_0,user_0,...,False,None,None,False,2026-03-07 19:40:59-05:00,1772930459,,0.0,,None
1,tiktok,hashtag,nikeshoes,nikeshoes,mock_video_nikeshoes_1,1772926859,Mock video about nikeshoes #nikeshoes #fashion,"[nikeshoes, fashion, style]",mock_author_1,user_1,...,False,None,None,False,2026-03-07 19:41:00-05:00,1772930460,,0.0,,None
2,tiktok,hashtag,nikeshoes,nikeshoes,mock_video_nikeshoes_2,1772923259,Mock video about nikeshoes #nikeshoes #fashion,"[nikeshoes, fashion, style]",mock_author_2,user_2,...,False,None,None,False,2026-03-07 19:41:01-05:00,1772930461,,0.0,,None
3,tiktok,hashtag,nikeshoes,nikeshoes,mock_video_nikeshoes_3,1772919659,Mock video about nikeshoes #nikeshoes #fashion,"[nikeshoes, fashion, style]",mock_author_3,user_3,...,False,None,None,False,2026-03-07 19:41:02-05:00,1772930462,,0.0,,None
4,tiktok,hashtag,nikeshoes,nikeshoes,mock_video_nikeshoes_4,1772916059,Mock video about nikeshoes #nikeshoes #fashion,"[nikeshoes, fashion, style]",mock_author_4,user_4,...,False,None,None,False,2026-03-07 19:41:03-05:00,1772930463,,0.0,,None

In [2]:
df[["brand", "source_query", "product_category", "content_type", "caption_text", "engagement_rate"]].sample(10, random_state=0)

,brand,source_query,product_category,content_type,caption_text,engagement_rate
110,adidas,adidasreview,uncategorized,shopping_haul,Mock video about adidasreview #adidasreview #f...,0.085000
112,adidas,adidasreview,uncategorized,shopping_haul,Mock video about adidasreview #adidasreview #f...,0.058400
143,nike,nike,uncategorized,None,Mock video about nike #nike #fashion,0.058400
7,nike,nikesneakers,shoes,None,Mock video about nikesneakers #nikesneakers #f...,0.077500
44,nike,nikebasketball,uncategorized,None,Mock video about nikebasketball #nikebasketbal...,0.075000
101,adidas,adidastraining,uncategorized,None,Mock video about adidastraining #adidastrainin...,0.061333
122,adidas,adidasgazelle,shoes,None,Mock video about adidasgazelle #adidasgazelle ...,0.077500
66,adidas,adidasshoes,shoes,None,Mock video about adidasshoes #adidasshoes #fas...,0.061333
85,adidas,adidasoutfit,apparel,None,Mock video about adidasoutfit #adidasoutfit #f...,0.075000
86,adidas,adidaslook,apparel,None,Mock video about adidaslook #adidaslook #fashion,0.061333

In [3]:
df.groupby(["brand", "product_category"])["engagement_rate"].agg(["count", "mean"])

                         count      mean
brand  product_category
adidas apparel              20  0.071447
       shoes                35  0.071447
       uncategorized        30  0.071447
nike   apparel              20  0.071447
       shoes                15  0.071447
       uncategorized        40  0.071447

In [4]:
df["content_type"].value_counts(dropna=False)

content_type
None             150
shopping_haul     10
Name: count, dtype: int64

In [6]:
import pandas as pd

feature_path = "data/processed/feature/feature_test.parquet"
df = pd.read_parquet(feature_path)

cols = [
    "brand",
    "source_query",
    "brand_style",
    "product_line",
    "product_category",
    "content_type",
    "engagement_rate",
]
df[cols].sample(20, random_state=0)

,brand,source_query,brand_style,product_line,product_category,content_type,engagement_rate
110,adidas,adidasreview,None,None,uncategorized,shopping_haul,0.085000
112,adidas,adidasreview,None,None,uncategorized,shopping_haul,0.058400
143,nike,nike,None,None,uncategorized,None,0.058400
7,nike,nikesneakers,None,None,shoes,None,0.077500
44,nike,nikebasketball,performance,None,uncategorized,None,0.075000
101,adidas,adidastraining,performance,None,uncategorized,None,0.061333
122,adidas,adidasgazelle,retro,gazelle,shoes,None,0.077500
66,adidas,adidasshoes,None,None,shoes,None,0.061333
85,adidas,adidasoutfit,None,None,apparel,None,0.075000
86,adidas,adidaslook,None,None,apparel,None,0.061333
133,adidas,adidasspezial,None,spezial,shoes,None,0.058400
92,adidas,adidasfootball,performance,None,uncategorized,None,0.077500
26,nike,nikefit,None,None,apparel,None,0.061333
146,nike,jordan,None,jordan,shoes,None,0.085000
119,adidas,adidasgazelle,retro,gazelle,shoes,None,0.085000
62,nike,niketech,technical,tech_fleece,apparel,None,0.077500
51,nike,niketiktok,None,None,uncategorized,None,0.061333
97,adidas,adidasrunning,performance,None,uncategorized,None,0.077500
128,adidas,adidasgazelles,retro,gazelle,shoes,None,0.058400
90,adidas,adidaslook,None,None,apparel,None,0.075000

In [11]:
df.groupby(["brand", "product_category", "content_type"])["engagement_rate"] \
  .agg(["count", "mean"]) \
  .reset_index() \
  .sort_values("count", ascending=False)

    brand product_category   content_type  count      mean
0  adidas    uncategorized  shopping_haul      5  0.071447
1    nike    uncategorized  shopping_haul      5  0.071447

In [9]:
df[df["product_category"] == "shoes"][["source_query", "normalized_hashtags", "product_line", "product_category"]].head()

  source_query          normalized_hashtags product_line product_category
0    nikeshoes  [nikeshoes, fashion, style]         None            shoes
1    nikeshoes  [nikeshoes, fashion, style]         None            shoes
2    nikeshoes  [nikeshoes, fashion, style]         None            shoes
3    nikeshoes  [nikeshoes, fashion, style]         None            shoes
4    nikeshoes  [nikeshoes, fashion, style]         None            shoes